### ISSUE TITLE
[Feature Request] Scan folders only by name

### ISSUE THREAD

**Issue by castillo92** [rullzer/previewgenerator#138]
Hello! I use your software very much and, first of all, I have to say that it's amazing! Thanks you very much for your effort!

But, can you add the option to scan only certain folders? adding an opcion like:
...to scan only folders witch names are "photos" or "Photos" or "hollidays"
`./occ config:app:set --value="photos Photos hollidays" previewgenerator foldermask`

I think it's easy, because it's only necessary change a little part of the code of scanner and ignore folders witch names are different with an If conditional.

I could try to create a pull request, but I dont know exactly where is the code, sorry.

Regards!

**Comment by DKlemann** [comment]
The code is in lib/Command/Generate.php
You'd have to add an option in configure() and use it in execute().

**Comment by castillo92** [comment]
> The code is in lib/Command/Generate.php
> You'd have to add an option in configure() and use it in execute().

Sorry, but I dont have enought knowledge to code the function

**Comment by focus121** [comment]
This also would eventually solve a probelm I have. I activated the server-side encryption to try/use the new E2EE feature. But didn't activate "Encrypt the home storage". So all data on my server storage isn't encrypted. E2EE works now. But preview-generator doesn't. When I run it I get 

"Encryption is enabled. Aborted."

But that shouldn't be a problem because pictures aren't encrypted (except on external storage or in folders where encryption is activated by apps).
