### ISSUE TITLE
Too many arguments (occ)

### ISSUE THREAD

**Issue by stavros-k** [rullzer/previewgenerator#212]
When running `occ config:app:set --value="32 64 1024"  previewgenerator squareSizes` i get error `Too many arguments` 
When i try to run it with only one value eg `occ config:app:set --value="32"  previewgenerator squareSizes` It works.

```
occ config:app:set previewgenerator widthSizes  --value="256 384"

                                                                  
  Too many arguments, expected arguments "command" "app" "name".  
                                                                  

config:app:set [--output [OUTPUT]] [--value VALUE] [--update-only] [--] <app> <name>
```

Running Preview Generator 3.0.1 
Nextcloud 20.0.3

**Comment by strugee** [comment]
Try `--value "256 384"` (without the `=` as the help output says.

**Comment by stavros-k** [comment]
> Try `--value "256 384"` (without the `=`) as the help output says.

```
occ config:app:set --value "256 384" previewgenerator squareSizes

                                                                  
  Too many arguments, expected arguments "command" "app" "name".  
                                                                  

config:app:set [--output [OUTPUT]] [--value VALUE] [--update-only] [--] <app> <name>
```

Same thing :/

**Comment by gillesF78** [comment]
Same problem for me : 
`root@nextcloudpi:/home/pi# occ config:app:set previewgenerator squareSizes --value '32 256'


  Too many arguments, expected arguments "command" "app" "name".


config:app:set [--output [OUTPUT]] [--value VALUE] [--update-only] [--] <app> <name>
`

**Comment by stavros-k** [comment]
Bumping.. Is this really a bug, or we doing something wrong?

**Comment by TGreeneIII** [comment]
I've been getting the same errors. When I add a comma between the values, e.g. --value="256,384", the command runs successfully. However, I don't know for sure if it's parsed correctly by the previewgenerator.

**Comment by stavros-k** [comment]
> I've been getting the same errors. When I add a comma between the values, e.g. --value="256,384", the command runs successfully. However, I don't know for sure if it's parsed correctly by the previewgenerator.

Tried it and after generating previews, seems to generate too many.

PS. Also have the same problem on 
NC: 21b7
PrevGen: 3.1.0

**Comment by stavros-k** [comment]
I'm closing this issue, seems to be a linuxserver docker specific problem, On official docker works as it should. Found a temporary solution. More info in https://github.com/linuxserver/docker-nextcloud/issues/179

**Comment by stavros-k** [comment]
I'm closing this issue, seems to be a linuxserver docker specific problem, On official docker works as it should. Found a temporary solution. More info in https://github.com/linuxserver/docker-nextcloud/issues/179

**Comment by yawicz** [comment]
Sorry but I actually don't think this issue is resolved. I still had the very same problem today _not_ running on docker or linuxserver, so the suggested solution did not change anything for me.

My setup:
Raspberry Pi 4B 8GB
Ubuntu 20.10 x64
Nextcloud 20.0.5
Previewgenerator 3.1.1

Same error message as above when for example running:
`sudo -u www-data ./occ config:app:set previewgenerator widthSizes  --value="256 384"`

I also tried many suggested variants, like removing the = after value, adding a comma in between, etc.
Adding a comma for example changes the way the values are stored, thats probably why it did not work for you either, @stavros-k . If you run `sudo -u www-data ./occ config:list` afterwards, you will see that the values are then actually stored like this: `"squareSizes": "32,256",`, so the app will probably just ignore them / can't read them.

The solution I found (the classic):
Using single quotes instead of double quotes works. Double quotes still work for single values after the value= part. But as soon as you want to set more than one value at once, it only works with single quotes, at least for me.

So this is the working way to do it as of now for me:
`sudo -u www-data ./occ config:app:set previewgenerator widthSizes  --value='256 384'`

Results in:
`Config value widthSizes for app previewgenerator set to 256 384`

So I'm not sure what exactly is the problem or what changed recently, but there must have changed something somewhere in the backend, either of Nextcloud or the Previewgenerator app.
So either this change should be reverted, or the documentation of Previewgenerator here should be updated, IMO.

Anyways, thanks for the great app and I hope I could be of help to someone who might have the same error. ;-)

**Comment by robertpenz** [comment]
With a shell open from a Linux system, the call works only this way

```occ config:app:set previewgenerator squareSizes --value=\"32 256\"
Config value squareSizes for app previewgenerator set to 32 256
```

**Comment by alexisindesign** [comment]
Working command:

`docker exec -u root nextcloud-app runuser -u www-data -- php occ --no-warnings config:app:set --value="32 64 1024" previewgenerator squareSizes`

**Comment by keesfluitman** [comment]
> With a shell open from a Linux system, the call works only this way
> 
> ```
> # occ config:app:set previewgenerator squareSizes --value=\"32 256\"
> Config value squareSizes for app previewgenerator set to 32 256
> ```

Why are the \ necessary? It used to work for me, but this seemed to do the trick.
