### ISSUE TITLE
Stupid question: what is the difference between pre-generate and generate-all?

### ISSUE THREAD

**Issue by MG2R** [rullzer/previewgenerator#60]
I tried reading the README and glancing at the code, neither gave me a clear picture on the difference between both. Both seem to generate previews?

**Comment by JSoko** [comment]
As you can rad in the docu:

> > preview:generate-all [user-id]
> 
> Loop over all files and try to generate previews for them. If user-id is supplied just loop over the files for that user.
> preview:pre-generate
> 
> Do the actual pregeneration. This means only for new or modified files (since the app was enabled).

generate-all hadles all files in your installation; pre-generate handles only new or modified files. 
So, especialy for existing NC-Installations generate-all can last very long...
...pre-generate doesn't handle old files, witch are not changed since the app has been activated...

**Comment by MG2R** [comment]
Thanks!
