### ISSUE TITLE
Preview in file list is still slow when using shared link

### ISSUE THREAD

**Issue by lfigiel** [rullzer/previewgenerator#79]
In web interface the preview in file list and thumbnail works much faster now but when using a shared link only thumbnail is faster. Preview in file list is as slow as it used to be.

**Comment by rullzer** [comment]
This is because the preview there is done by the gallery app. And this does some more processing (it is still on the list to fix). So long story short. It is actually using the cached preview. Just it first construct some stuff in RAM instead of directly streaming the image.

Nothing this app can fix.
